logo: '/images/milo.png'
topNav:
  globalLinks:
    display: true
    links:
    - title: 'Home'
      url: '/'
    - title: 'Get Started'
      url: '/get-started/'
  dropdown:
    display: true
    name: "Dropdown"
    url: "/"             
    links:              
      - name: "About Us"
        url: "/about"
      - name: "Services"
        url: "/services"
      - name: "Contact"
        url: "/contact"
names:
  organization: 'Emdash'
  product: 'MiloDocs'
version: 
  major: 0
  minor: 0
  patch: 3
article:
  childArticles:
    display: true
    count: 7 
    titleTrunc: 90
    descTrunc: 90
  nextPrev: 
    display: true
    trunc: 35
  chat: 
    display: true
  # Sidebar TOC (right sidebar)
  toc: 
    display: true
  # Inline components (within article content)
  inlineToc:
    display: false
    showProgress: false
  pageResources:
    display: true
  # Content status warnings (draft and expiry alerts)
  statusWarnings:
    display: true
  # Enhanced metadata section (dates, author, reading time, word count)
  metadata:
    display: true
  # Related content section (shows related pages in same section)
  relatedContent:
    display: true

# Development & Debug Settings
debug: false  # Set to true to enable template debugging information
