# Server configuration for optimal performance
headers:
  - for: "/css/**"
    values:
      Cache-Control: "public, max-age=31536000, immutable"
  - for: "/js/**"
    values:
      Cache-Control: "public, max-age=31536000, immutable"
  - for: "/images/**"
    values:
      Cache-Control: "public, max-age=31536000"
  - for: "/icons/**"
    values:
      Cache-Control: "public, max-age=31536000"
  - for: "/*.woff2"
    values:
      Cache-Control: "public, max-age=31536000, immutable"
  - for: "/**"
    values:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"