openapi: 3.0.0
info:
  version: 1.0.1
  title: Bolt API Reference
  description: |
    Postman Collection:

    [![](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/9136127-55d2bde1-a248-473f-95b5-64cfd02fb445?action=collection%2Ffork&collection-url=entityId%3D9136127-55d2bde1-a248-473f-95b5-64cfd02fb445%26entityType%3Dcollection%26workspaceId%3D78beee89-4238-4c5f-bd1f-7e98978744b4#?env%5BBolt%20Sandbox%20Environment%5D=W3sia2V5IjoiYXBpX2Jhc2VfdXJsIiwidmFsdWUiOiJodHRwczovL2FwaS1zYW5kYm94LmJvbHQuY29tIiwidHlwZSI6ImRlZmF1bHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InRrX2Jhc2UiLCJ2YWx1[...]

    ## About
     A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

     Note: You must also reference the [Merchant Callback API](/api-merchant) when building a managed checkout custom cart integration
tags:
  - name: Webhooks
    description: |
      Set up webhooks to notify your backend of events within Bolt. These webhooks can communicate with your OMS or other systems to keep them up to date with Bolt. See our related guide on [Webhooks](https://help.bolt.com/get-started/during-checkout/webhooks/).
  - name: Testing
    description: |
      The testing endpoint allows you to test various functionality within Bolt. Create a test credit card to process a test payment in your store. You can also simulate tracking an order’s shipment and programmatically create customer accounts to use as dummy data. See our related guide on [Testing](https://help.bolt.com/developers/production-readiness-guides/test-cards/).
  - name: Products
    description: |
      Products within Bolt represent the products on your ecommerce server or store. Use this resource to create products and retrieve the Bolt product catalog. You can also create a store using this resource.
  - name: OAuth
    description: |
      Use this endpoint to retrieve an OAuth token. Use the token to allow your ecommerce server to make calls to the Account endpoint and create a one-click checkout experience for shoppers. See related guide [Fetch OAuth Token](https://help.bolt.com/products/accounts/direct-api/oauth-guide/).
  - name: Account
    description: |
      Use the Account endpoint to view and manage customer accounts. Perform actions such as creating an account, updating an address, or adding a payment method. This endpoint is for merchants using the Accounts Package. See our related guide on [Bolt OAuth](https://help.bolt.com/developers/bolt-oauth/).
  - name: Payments
    description: |
      Use the Payments API to tokenize and process alternative payment methods with Bolt. This API is for the Bolt Accounts package. See our related guide on [PayPal for Accounts Implementation](https://help.bolt.com/products/accounts/direct-api/paypal-embedded/).
  - name: Configuration
    description: |
      Use this resource to retrieve and set Merchant Callback URLs. Bolt uses these URLs to exchange information with your commerce server. See our related guide [About the Merchant Callback API](https://help.bolt.com/products/checkout/custom-cart-guides/how-to-integrate/merchant-api/).   
  - name: Orders
    description: |
      Use the Orders API to interact with the customer's cart throughout the checkout process. Pre-checkout, perform actions such as validating inventory, verifying discounts, and calculating taxes. Post-checkout, share shipping information so your customer can track their order. You'll interact with the [Merchant API](https://help.bolt.com/api-merchant/) to keep the servers in sync with any changes the customer makes to their cart. See our related guide [Create a Bolt Order Token](https://help.[...]
  - name: Statements
    description: |
      [Statements](/merchants/references/financials/statements/) are available in the Merchant Dashboard for merchants who use Bolt Payments as their processor. Merchants using other processors do not receive these statements.
  - name: Transactions
    description: |
      Use the Transactions endpoint to authorize payments when the shopper checks out and handle post authorization actions such as captures and refunds. You can use a shopper's existing saved payment information or tokenize new payment information with the [Bolt Tokenizer](https://help.bolt.com/api-tokenizer/). Bolt Authorize Transaction types fall into one of three categories: a logged-in shopper checking out with a saved payment method, any type of shopper checking out with a new payment meth[...]
servers:
  - url: 'https://api.bolt.com'
    description: The Production URL (Live Data).
  - url: 'https://api-sandbox.bolt.com'
    description: The Sandbox URL (Test Data).
  - url: 'https://api-staging.bolt.com'
    description: The Staging URL (Staged Data).
components:
  securitySchemes:
    OAuth:
      description: |
        Bolt utilizes the OAuth flow that developers can use to attain access to Bolt Account data via APIs.
        For all APIs that require authorization, please provide your `access_token` returned from `/v1/oauth/token` via the basic auth bearer header `Authorization: bearer ${TOKEN}`.
        [Read more about the OAuth token endpoint.](/api-bolt/#tag/OAuth)
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.bolt.com/v1/oauth/authorize'
          refreshUrl: 'https://api.bolt.com/v1/oauth/token'
          scopes:
            bolt.account.manage: This scope grants permissions to perform read/edit/delete actions on Bolt Account data
            bolt.account.view: This scope grants permissions to perform read only actions on Bolt Account data
            openid: This scope grants permissions that enable Bolt SSO by granting an id token JWT that stores account data. Not used in v1/account endpoints
          tokenUrl: 'https://api.bolt.com/v1/oauth/token'
      type: oauth2
    X-API-Key:
      description: Admins and Developers can obtain their Bolt API key from the Bolt Merchant Dashboard.
      in: header
      name: X-API-Key
      type: apiKey
paths:
  /v1/account:
    get:
      description: 'Fetch a shopper''s account details to pre-fill checkout fields. This request must come from your backend for security purposes, as it requires the use of your private key to authenticate. For PCI compliance, only limited information is returned for each credit card available in the shopper’s wallet.'
      operationId: getAccount
      security:
        - OAuth:
            - bolt.account.manage
            - bolt.account.view
          X-API-Key: []
      summary: Get Account Details
      tags:
        - Account
    post:
      description: Create a Bolt shopping account.
      operationId: createAccount
      security:
        - X-API-Key: []
      summary: Create Bolt Account
      tags:
        - Account
  /v1/account/profile:
    patch:
      description: Update the identifiers for a shopper's profile (first name or last name).
      operationId: updateAccountProfile
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Update Profile
      tags:
        - Account
  /v1/account/addresses:
    post:
      description: Add an address to a shopper's account address book.
      operationId: addAddress
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Add Address
      tags:
        - Account
  '/v1/account/addresses/{id}':
    delete:
      description: |
        Deletes an existing address in a shopper's address book.
      operationId: deleteAddress
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Delete Address
      tags:
        - Account
    post:
      description: |
        Replace an existing address in a shopper's address book.
        These changes delete the existing address and create a new one.
      operationId: replaceAddress
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Replace Address
      tags:
        - Account
    put:
      description: |
        Edit an existing address in a shopper's address book.
        This endpoint fully replaces the information for an existing address while retaining the same address ID.
      operationId: editAddress
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Edit Address
      tags:
        - Account
  /v1/account/exists:
    get:
      description: 'Check whether an account exists using one of `email`, `phone`, or `sha256_email` as the unique identifier.'
      operationId: detectAccount
      summary: Detect Account
      tags:
        - Account
      security: []
  /v1/account/payment_methods:
    post:
      description: |
        Add a payment method to a shopper's Bolt account Wallet. For security purposes, this request must come from your backend because authentication requires the use of your private key.

        **Note**: Before using this API, the credit card details must be tokenized using Bolt's JavaScript library function, which is documented in [Install the Bolt Tokenizer](https://help.bolt.com/developers/references/bolt-tokenizer).
      operationId: addPaymentMethod
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Add Payment Method
      tags:
        - Account
  /v1/payments:
    post:
      description: |
        Initialize a Bolt payment token that will be used to reference this payment to Bolt when it is updated or finalized. NOTE: The authorization header is NOT required for payments associated with users who do not have a Bolt account.
      operationId: initializePayment
      security:
        - OAuth:
            - bolt.account.manage
        - X-API-Key: []
      summary: Initialize Payment
      tags:
        - Payments
  '/v1/payments/{id}':
    post:
      description: |
        Update a Bolt payment using the token given after initializing a payment.  Updates will completely replace the original top-level resource (for example, if a cart is sent in with the request it will replace the existing cart).  Any included object should be sent as complete object. NOTE: The authorization header is NOT required for payments associated with users who do not have a Bolt account.
      operationId: updatePayment
      security:
        - OAuth:
            - bolt.account.manage
        - X-API-Key: []
      summary: Update Payment
      tags:
        - Payments
  'v1/payments/{id}/finalize':
    post:
      description: |
        Finalize a Bolt Payment. NOTE: The authorization header is NOT required for payments associated with users who do not have a Bolt account.
      operationId: finalizePayment
      security:
        - OAuth:
            - bolt.account.manage
        - X-API-Key: []
      summary: Finalize Payment
      tags:
        - Payments
  '/v1/account/payment_methods/{payment_method_id}':
    delete:
      description: Delete a saved payment method from a shopper's Bolt account Wallet.
      operationId: deletePaymentMethod
      security:
        - OAuth:
            - bolt.account.manage
          X-API-Key: []
      summary: Delete Payment Method
      tags:
        - Account
  /v1/merchant/callbacks:
    get:
      description: Retrieves callbacks URLs for a Bolt merchant division.
      operationId: getMerchantCallbacks
      security:
        - X-API-Key: []
      summary: Get Callback URLs
      tags:
        - Configuration
    post:
      description: Configure callbacks URLs for a Bolt merchant division. This will store or override only the callback URLs that are specified in the request. Operations are fully transactional.
      operationId: setMerchantCallbacks
      security:
        - X-API-Key: []
      summary: Set Callback URLs
      tags:
        - Configuration
  /v1/merchant/identifiers:
    get:
      description: 'This endpoint returns the merchant''s public ID and the [publishable key](https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/custom-cart-guides/how-to-integrate/) related to the merchant division.'
      operationId: getMerchantIdentifiers
      security:
        - X-API-Key: []
      summary: Get Merchant Identifiers
      tags:
        - Configuration
  /v1/merchant/orders:
    post:
      description: 'Make a request to this endpoint to create a Bolt order, generate a Bolt order token, and initiate the checkout process. A Bolt order token is required for Bolt orders; see Non-Bolt orders for alternative use cases.'
      operationId: createOrderToken
      security:
        - X-API-Key: []
      summary: Create Order Token
      tags:
        - Orders
  /v1/merchant/statement:
    post:
      description: Get a pre-signed URL for the requested statement file.
      operationId: getStatements
      security:
        - X-API-Key:
            - X-API-Key
      summary: Fetch a Statement
      tags:
        - Statements
  /v1/merchant/track_shipment:
    post:
      description: |
        Send the carrier and order tracking number to Bolt (after a label has been printed). Bolt then uses EasyPost to forward ongoing tracking event updates to the shopper. This request must include **all** items included in the shipment; their references must also match those found in the original cart generation.
      operationId: trackOrder
      security:
        - X-API-Key:
            - X-API-Key
      summary: Send order tracking details
      tags:
        - Orders
  /v1/merchant/transactions/authorize:
    post:
      description: |
        This endpoint authorizes card payments and has three main use cases:
        * • Authorize a payment using an unsaved payment method for a guest or logged-in shopper.
        * • Authorize a payment using a saved payment method for a logged-in shopper.
        *  • Re-charge a previous transaction using the `credit_card_id` of the transaction.
      operationId: authorizeTransaction
      security:
        - OAuth: []
          X-API-Key: []
      summary: Authorize a Card
      tags:
        - Transactions
  /v1/merchant/transactions/capture:
    post:
      description: |
        This captures funds for the designated transaction. A capture can be done for any partial amount or for the total authorized amount.

        Although the response returns the standard `transaction_view` object, only `captures` and either `id` or `reference` are needed.
      operationId: captureTransaction
      security:
        - X-API-Key: []
      summary: Capture a Transaction
      tags:
        - Transactions
  /v1/merchant/transactions/credit:
    post:
      description: This refunds a captured transaction. Refunds can be done for any partial amount or for the total authorized amount. These refunds are processed synchronously and return information about the refunded transaction in the standard `transaction_view` object.
      operationId: refundTransaction
      security:
        - X-API-Key: []
      summary: Refund a Transaction
      tags:
        - Transactions
  /v1/merchant/transactions/review:
    post:
      description: This endpoint is used to manually approve or reject orders for a specified transaction.
      operationId: reviewTransaction
      security:
        - X-API-Key: []
      summary: Review Transaction
      tags:
        - Transactions
  /v1/merchant/transactions/void:
    post:
      description: |
        This voids the authorization for a given transaction. Voids must be completed before the authorization is captured.
        In the request, either `transaction_id` or `transaction_reference` is required.
        Although the response returns the standard `transaction_view` object, only `status` and either `id` or `reference` are needed.
      operationId: voidTransaction
      security:
        - X-API-Key: []
      summary: Void a Transaction
      tags:
        - Transactions
  '/v1/merchant/transactions/{REFERENCE}':
    get:
      description: |
        This allows you to pull the full transaction details for a given transaction.

         **Note**: All objects and fields marked `required` in the Transaction Details response are also **nullable**. This includes any sub-components (objects or fields) also marked `required`.
      operationId: getTransactionDetails
      security:
        - X-API-Key: []
      summary: Transaction Details
      tags:
        - Transactions
    patch:
      description: This allows you to update certain transaction properties post-authorization.
      operationId: updateTransaction
      security:
        - X-API-Key: []
      summary: Update a Transaction
      tags:
        - Transactions
  /v1/oauth/token:
    post:
      description: |
        Endpoint for receiving access, ID, and refresh tokens from Bolt's OAuth server. 

        To use this endpoint, first use the Authorization Code Request flow by using the `authorization_code` Grant Type (`grant_type`). Then, in the event that you would need a second or subsequent code, use the `refresh_token` value returned from a successful request as the `refresh_token` input value in your subsequent `refresh_token` Grant Type (`grant_type`) request.

         **Reminder - the Content-Type of this request must be application/x-www-form-urlencoded**
      operationId: OAuthToken
      summary: OAuth Token Endpoint
      tags:
        - OAuth
  /v1/products/catalog:
    get:
      description: This endpoint returns a list of products when given a valid `merchant_division_id`.
      operationId: getProductsCatalog
      security:
        - X-API-Key: []
      summary: Get Products Catalog
      tags:
        - Products
  /v1/catalog/custom/product:
    post:
      description: Put Custom Product
      operationId: addCustomProduct
      security:
        - X-API-Key:
            - X-API-Key
      tags:
        - Products
  /v1/catalog/custom/store:
    post:
      description: Put Custom Store
      operationId: createCustomStore
      security:
        - X-API-Key:
            - X-API-Key
      tags:
        - Products
  /v1/remote_checkout/order:
    post:
      description: |
        This is used for publisher implementation use cases. After calling Bolt to check product inventory for availability, call the `/remote_checkout/order` endpoint to create a Bolt order, generate a Bolt order token, and initiate the checkout process. 
      operationId: createRemoteOrder
      security:
        - X-API-Key: []
      summary: Create order token (remote)
      tags:
        - Orders
  /v1/shipments/mock_bolt_shipping:
    post:
      description: This endpoint simulates tracking an order's shipment and is for testing purposes only.
      operationId: testShipping
      security:
        - X-API-Key: []
      summary: Test Shipping
      tags:
        - Orders
        - Testing
  /v1/webhooks:
    get:
      description: Find webhook configurations belonging to a merchant division. Results are limited to only show webhooks authorized by the X-API-Key.
      operationId: queryWebhooks
      security:
        - X-API-Key: []
      summary: Query Webhooks
      tags:
        - Webhooks
    post:
      description: 'Create a new webhook to receive notifications from Bolt about various events, such as transaction status. Webhooks must have unique configuration.'
      operationId: createWebhook
      security:
        - X-API-Key: []
      summary: Create Bolt Webhook
      tags:
        - Webhooks
  '/v1/webhooks/{webhook_id}':
    delete:
      description: Delete a Bolt webhook. Provide an authorized X-API-Key to perform this action.
      operationId: deleteWebhook
      security:
        - X-API-Key: []
      summary: Delete a Bolt Webhook
      tags:
        - Webhooks
    get:
      description: Get Webhook information by its Webhook ID. Results only include webhooks authorized by the X-API-Key.
      operationId: getWebhook
      security:
        - X-API-Key: []
      summary: Get Webhook
      tags:
        - Webhooks
  /v1/testing/shopper/create:
    post:
      description: Create a Bolt shopper account for testing purposes. Available for sandbox use only and the created  account will be recycled after a certain time.
      operationId: createTestingShopperAccount
      security:
        - X-API-Key: []
      summary: Create Testing Shopper Account
      tags:
        - Testing
  /v1/testing/card_token:
    get:
      description: This endpoint fetches a new credit card token for Bolt's universal test credit card number `4111 1111 1111 1004`. This is for testing and is available only in sandbox.
      operationId: getTestCreditCardToken
      security:
        - X-API-Key: []
      summary: Fetch a Test Credit Card Token
      tags:
        - Testing
security:
  - X-API-Key: []
  - OAuth:
      - bolt.account.manage
      - bolt.account.view
